// Generated by gencpp from file face_detect/facebox.msg
// DO NOT EDIT!


#ifndef FACE_DETECT_MESSAGE_FACEBOX_H
#define FACE_DETECT_MESSAGE_FACEBOX_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace face_detect
{
template <class ContainerAllocator>
struct facebox_
{
  typedef facebox_<ContainerAllocator> Type;

  facebox_()
    : top(0)
    , left(0)
    , width(0)
    , height(0)  {
    }
  facebox_(const ContainerAllocator& _alloc)
    : top(0)
    , left(0)
    , width(0)
    , height(0)  {
  (void)_alloc;
    }



   typedef uint16_t _top_type;
  _top_type top;

   typedef uint16_t _left_type;
  _left_type left;

   typedef uint16_t _width_type;
  _width_type width;

   typedef uint16_t _height_type;
  _height_type height;




  typedef boost::shared_ptr< ::face_detect::facebox_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::face_detect::facebox_<ContainerAllocator> const> ConstPtr;

}; // struct facebox_

typedef ::face_detect::facebox_<std::allocator<void> > facebox;

typedef boost::shared_ptr< ::face_detect::facebox > faceboxPtr;
typedef boost::shared_ptr< ::face_detect::facebox const> faceboxConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::face_detect::facebox_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::face_detect::facebox_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace face_detect

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'face_detect': ['/home/corvin/YoYoRobot/YoYoRobot/src/face_detect/msg'], 'geometry_msgs': ['/opt/ros/kinetic/share/geometry_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::face_detect::facebox_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::face_detect::facebox_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::face_detect::facebox_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::face_detect::facebox_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::face_detect::facebox_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::face_detect::facebox_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::face_detect::facebox_<ContainerAllocator> >
{
  static const char* value()
  {
    return "84a8772d0473c9a0b5e2268e6352f57e";
  }

  static const char* value(const ::face_detect::facebox_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x84a8772d0473c9a0ULL;
  static const uint64_t static_value2 = 0xb5e2268e6352f57eULL;
};

template<class ContainerAllocator>
struct DataType< ::face_detect::facebox_<ContainerAllocator> >
{
  static const char* value()
  {
    return "face_detect/facebox";
  }

  static const char* value(const ::face_detect::facebox_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::face_detect::facebox_<ContainerAllocator> >
{
  static const char* value()
  {
    return "uint16 top\n\
uint16 left\n\
uint16 width\n\
uint16 height\n\
";
  }

  static const char* value(const ::face_detect::facebox_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::face_detect::facebox_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.top);
      stream.next(m.left);
      stream.next(m.width);
      stream.next(m.height);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER;
  }; // struct facebox_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::face_detect::facebox_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::face_detect::facebox_<ContainerAllocator>& v)
  {
    s << indent << "top: ";
    Printer<uint16_t>::stream(s, indent + "  ", v.top);
    s << indent << "left: ";
    Printer<uint16_t>::stream(s, indent + "  ", v.left);
    s << indent << "width: ";
    Printer<uint16_t>::stream(s, indent + "  ", v.width);
    s << indent << "height: ";
    Printer<uint16_t>::stream(s, indent + "  ", v.height);
  }
};

} // namespace message_operations
} // namespace ros

#endif // FACE_DETECT_MESSAGE_FACEBOX_H
